version: "3.9"
services:
  dev-finder-db:
    image: postgres
    restart: always
    container_name: duo-dev-connect-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 10123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: